# Generated by Django 4.1.7 on 2023-05-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0007_alter_owner_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="owner",
            name="phone",
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
    ]
